name: Build Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure the project
        run: |
          ./scripts/configure.sh

      - name: Build
        run: |
          ./scripts/build.sh
